version: '3.7'
services:
  web:
    container_name: employee_book_web
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: rails s -b 0.0.0.0
    environment:
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      DATABASE_URL: postgres://postgres:@db/employee_book
    links:
      - db
    depends_on:
      - db

  adm:
    image: dpage/pgadmin4
    volumes:
      - /Users/tmp_db/employee_book:/var/lib/pgadmin/storage
    ports:
      - "8888:80"
      - "443:443"
    environment:
       PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
       PGADMIN_DEFAULT_PASSWORD: 1234567890

  db:
    image: postgres:10.0
    container_name: employee_book_db
    volumes:
      - /Users/tmp_db/employee_book:/var/employee_book/lib/postgresql/data
    environment:
      TZ: Asia/Phnom_Penh
      PGDATA: /var/employee_book/lib/postgresql/data
